### ISSUE TITLE
Max password length

### ISSUE THREAD

**Issue by darthmaim** [Georgi-Kalkovski/GW2Geary#3]
I can't register because the password I use is longer than 40 characters, which seems to be the limit you set in https://github.com/Georgi-Kalkovski/GW2Geary/blob/main/client/src/components/Register.js#L114. Please remove this upper limit.

Additionally, no error message is shown, the focus just jumps back to the password input when clicking "Register".

**Comment by Georgi-Kalkovski** [comment]
Password upper limitation has been removed.
