### ISSUE TITLE
 ⚠️ Data Leak !IMPORTANT!

### ISSUE THREAD

**Issue by darthmaim** [Georgi-Kalkovski/GW2Geary#4]
Already reported in #2 by @Orihkeks

I am able to access emails of other accounts, and am pretty confident after looking at the code I would be able to change usernames/passwords/emails of other users or even delete other users.

I suggest **taking your website offline immediately** until this issue is fixed. Please make sure to test all your API endpoints.

If you need help, you can for example join the GW2 Development Community Discord (https://discord.gg/zqeHCEg).

**Comment by Georgi-Kalkovski** [comment]
All known issues of dataleaks have been fixed with the help of @darthmaim and @hristov296. Thanks to @Orihkeks as well for the first issue on this matter.

**Comment by Georgi-Kalkovski** [comment]
All known issues of dataleaks have been fixed with the help of @darthmaim and @hristov296. Thanks to @Orihkeks as well for the first issue on this matter.
